// Generated by engineering-ruleset-plugin. Re-run the sync to update it;
// local edits are overwritten.
// Turns a Trivy JSON report into a merge decision and one sticky pull-request
// comment. Runs inside GitHub Actions; requires Node 18+ (global fetch).
//
// It: (1) flattens Trivy's nested report into findings, (2) works out which of
// them this pull request is answerable for, (3) applies the severity threshold,
// (4) posts a comment naming exactly what blocks, and exits 1 (block) or 0.
//
// The three filters are separate on purpose. Scope answers "did this PR bring
// it", threshold answers "is it bad enough", fixability answers "could the
// author do anything about it". A gate that fails any of those tests is a gate
// nobody can clear.
//
// Every function below is pure and exported, so the decision logic is unit
// tested directly rather than only through a rendered workflow.

import { readFileSync, appendFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export const SEVERITY_ORDER = ['UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const COMMENT_MARKER = '<!-- trivy-security -->';

const upper = (v) => String(v ?? '').toUpperCase();

/**
 * Flattens Trivy's report into one array of findings.
 *
 * Trivy nests differently per scanner — Vulnerabilities, Secrets and
 * Misconfigurations are separate arrays under each Result, with different field
 * names for the same ideas — so this is where that shape is normalised once.
 */
export function classify(report) {
  const findings = [];

  for (const result of report?.Results ?? []) {
    const target = result.Target ?? '';

    for (const v of result.Vulnerabilities ?? []) {
      findings.push({
        kind: 'vulnerability',
        severity: upper(v.Severity) || 'UNKNOWN',
        // For a lockfile the finding belongs to the file Trivy scanned, not to
        // the package — that is what makes changed-file scope meaningful.
        file: v.PkgPath || target,
        // A dependency finding has no line: it comes from a resolved package,
        // not a position in the file.
        line: null,
        id: v.VulnerabilityID ?? '',
        title: v.Title || v.Description?.split('\n')[0] || v.VulnerabilityID || '',
        pkg: v.PkgName ?? '',
        installed: v.InstalledVersion ?? '',
        // An empty FixedVersion means upstream has published no fix yet.
        fix: v.FixedVersion ?? '',
      });
    }

    for (const s of result.Secrets ?? []) {
      findings.push({
        kind: 'secret',
        severity: upper(s.Severity) || 'CRITICAL',
        file: target,
        line: s.StartLine ?? null,
        id: s.RuleID ?? '',
        title: s.Title || s.RuleID || 'hardcoded secret',
        pkg: '',
        installed: '',
        // A secret is always actionable: remove it and rotate it.
        fix: 'remove it from the code and rotate the credential',
      });
    }

    for (const m of result.Misconfigurations ?? []) {
      findings.push({
        kind: 'misconfiguration',
        severity: upper(m.Severity) || 'UNKNOWN',
        file: target,
        line: m.CauseMetadata?.StartLine ?? null,
        id: m.ID ?? '',
        title: m.Title || m.ID || '',
        pkg: '',
        installed: '',
        fix: m.Resolution ?? '',
      });
    }
  }

  return findings;
}

/** Normalises a path the way both Trivy and the GitHub API can be compared. */
const normalise = (p) => String(p ?? '').replace(/^\.\//, '').replace(/^\/+/, '');

/**
 * Whether this pull request is answerable for the finding.
 *
 * `repository` scope means every finding counts. `changed-files` means only the
 * files this pull request touched — so adopting the check does not block the
 * first unrelated PR on a finding that was already there.
 */
export function withinScope(finding, changedFiles, blockScope = 'changed-files') {
  if (blockScope === 'repository') return true;
  const touched = new Set((changedFiles ?? []).map(normalise));
  return touched.has(normalise(finding.file));
}

/**
 * Whether a finding should fail the check.
 *
 * All three tests must pass. `ignoreUnfixed` only ever applies to
 * vulnerabilities: a secret or a misconfiguration is always fixable by the
 * author, so "no fix available" is not a thing they can hide behind.
 */
export function isBlocking(finding, { blockOn = ['CRITICAL'], changedFiles = [], blockScope = 'changed-files', ignoreUnfixed = true } = {}) {
  if (!blockOn.map(upper).includes(upper(finding.severity))) return false;
  if (!withinScope(finding, changedFiles, blockScope)) return false;
  if (ignoreUnfixed && finding.kind === 'vulnerability' && !finding.fix) return false;
  return true;
}

/** Splits findings into what blocks the merge and what is merely reported. */
export function partition(findings, opts = {}) {
  const blocking = [];
  const reported = [];
  for (const f of findings ?? []) (isBlocking(f, opts) ? blocking : reported).push(f);
  return { blocking, reported };
}

/** Highest severity first, then by file, so the worst thing is read first. */
export function bySeverity(a, b) {
  const d = SEVERITY_ORDER.indexOf(upper(b.severity)) - SEVERITY_ORDER.indexOf(upper(a.severity));
  return d !== 0 ? d : String(a.file).localeCompare(String(b.file));
}

/** `CRITICAL 1, HIGH 2` — a count per severity, worst first, zeroes omitted. */
export function tally(findings) {
  const counts = new Map();
  for (const f of findings ?? []) counts.set(upper(f.severity), (counts.get(upper(f.severity)) ?? 0) + 1);
  return [...SEVERITY_ORDER].reverse().filter((s) => counts.get(s)).map((s) => `${s} ${counts.get(s)}`).join(', ');
}

const where = (f) => (f.line ? `${f.file}:${f.line}` : f.file);

/**
 * The sticky comment.
 *
 * A blocked pull request has to say what blocked it and what to do — a bare
 * "check failed" makes the author go hunting through a log, which is how a
 * security gate turns into something people route around.
 */
export function renderComment({ blocking, reported }, opts = {}) {
  const { blockOn = ['CRITICAL'], blockScope = 'changed-files', scanners = [], ignoreUnfixed = true } = opts;
  const scopeText = blockScope === 'repository' ? 'the whole repository' : 'files changed in this pull request';
  const footer =
    `\n\n<sub>Trivy · blocks on ${blockOn.map(upper).join(', ')} · scope: ${scopeText}` +
    `${ignoreUnfixed ? ' · vulnerabilities with no released fix are reported, not blocked' : ''}` +
    `${scanners.length ? ` · scanners: ${scanners.join(', ')}` : ''}</sub>`;

  const extras = reported.length
    ? `\n\n<details><summary>${reported.length} further finding(s) — reported, not blocking (${tally(reported)})</summary>\n\n` +
      [...reported].sort(bySeverity).map((f) => `- \`${f.severity}\` ${f.kind} · \`${where(f)}\` · ${f.title || f.id}`).join('\n') +
      `\n\n</details>`
    : '';

  if (blocking.length === 0) {
    return (
      `### ✅ Trivy security check passed\n\n` +
      (reported.length
        ? `No ${blockOn.map(upper).join('/')} findings in ${scopeText}.`
        : `No findings.`) +
      extras + footer
    );
  }

  const rows = [...blocking]
    .sort(bySeverity)
    .map((f) => {
      const what = f.pkg ? `${f.pkg} ${f.installed}`.trim() : f.title || f.id;
      const fix = f.fix ? f.fix : 'no fix published — remove or replace it';
      return `| \`${f.severity}\` | ${f.kind} | \`${where(f)}\` | ${f.id ? `\`${f.id}\` ` : ''}${what} | ${fix} |`;
    })
    .join('\n');

  return (
    `### 🚫 Trivy security check failed — merge blocked\n\n` +
    `**${blocking.length} ${blockOn.map(upper).join('/')} finding(s)** in ${scopeText}. ` +
    `Fix these, or remove them from this pull request, and push again — this check re-runs automatically.\n\n` +
    `| Severity | Kind | Where | What | Fix |\n|---|---|---|---|---|\n${rows}` +
    extras + footer
  );
}

// ------------------------------------------------------------------ execution
const {
  GITHUB_TOKEN,
  GITHUB_API_URL = 'https://api.github.com',
  GITHUB_STEP_SUMMARY,
  REPO,
  PR_NUMBER,
  TRIVY_REPORT = 'trivy-report.json',
  BLOCK_ON = 'CRITICAL',
  BLOCK_SCOPE = 'changed-files',
  SCANNERS = 'vuln,secret,misconfig',
  IGNORE_UNFIXED = 'true',
} = process.env;

const list = (v) => String(v ?? '').split(',').map((s) => s.trim()).filter(Boolean);

async function gh(path, { method = 'GET', body } = {}) {
  const res = await fetch(`${GITHUB_API_URL}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(`GitHub ${method} ${path} -> ${res.status}: ${(await res.text()).slice(0, 300)}`);
  return res.json();
}

async function changedFiles(owner, name) {
  const files = [];
  for (let page = 1; page <= 10; page += 1) {
    const batch = await gh(`/repos/${owner}/${name}/pulls/${PR_NUMBER}/files?per_page=100&page=${page}`);
    files.push(...batch.map((f) => f.filename));
    if (batch.length < 100) break;
  }
  return files;
}

async function upsertComment(owner, name, body) {
  const withMarker = `${COMMENT_MARKER}\n${body}`;
  const comments = await gh(`/repos/${owner}/${name}/issues/${PR_NUMBER}/comments?per_page=100`);
  const existing = comments.find((c) => (c.body || '').includes(COMMENT_MARKER));
  if (existing) {
    await gh(`/repos/${owner}/${name}/issues/comments/${existing.id}`, { method: 'PATCH', body: { body: withMarker } });
  } else {
    await gh(`/repos/${owner}/${name}/issues/${PR_NUMBER}/comments`, { method: 'POST', body: { body: withMarker } });
  }
}

async function main() {
  const [owner, name] = String(REPO || '').split('/');
  if (!owner || !name || !PR_NUMBER) throw new Error('Missing REPO or PR_NUMBER.');

  const opts = {
    blockOn: list(BLOCK_ON),
    blockScope: BLOCK_SCOPE,
    scanners: list(SCANNERS),
    ignoreUnfixed: IGNORE_UNFIXED === 'true',
  };

  const findings = classify(JSON.parse(readFileSync(TRIVY_REPORT, 'utf8')));
  opts.changedFiles = opts.blockScope === 'repository' ? [] : await changedFiles(owner, name);

  const parts = partition(findings, opts);
  const body = renderComment(parts, opts);

  await upsertComment(owner, name, body);
  if (GITHUB_STEP_SUMMARY) {
    try {
      appendFileSync(GITHUB_STEP_SUMMARY, `${body}\n`);
    } catch {
      /* the summary is a convenience; never fail the run over it */
    }
  }

  if (parts.blocking.length === 0) {
    console.log(`::notice::Trivy security check passed (${parts.reported.length} non-blocking finding(s)).`);
    process.exit(0);
  }
  for (const f of parts.blocking) {
    console.log(`::error file=${f.file}${f.line ? `,line=${f.line}` : ''}::${f.severity} ${f.kind}: ${f.title || f.id}`);
  }
  console.log(`::error::Trivy security check failed — ${parts.blocking.length} blocking finding(s).`);
  process.exit(1);
}

// Only run when executed directly, so importing this file in a test does not
// start talking to the GitHub API.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(async (error) => {
    console.error(error);
    // A scan that could not complete must not read as a scan that passed.
    console.log(`::error::Trivy security check could not complete: ${error.message}`);
    process.exit(1);
  });
}
